export const USER_UPDATE = 'USER_UPDATE';
export const USER_CREATE = 'USER_CREATE';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USER_CREATION_SUCCESS = 'USER_CREATION_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const PROTECTED_TEST = 'PROTECTED_TEST';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';

export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_CREATION_SUCCESS = 'PROJECT_CREATION_SUCCESS';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';

export const JOBS_FETCH_SUCCESS = 'JOBS_FETCH_SUCCESS';
export const JOB_FETCH_SUCCESS = 'JOB_FETCH_SUCCESS';
export const JOB_CREATION_SUCCESS = 'JOB_CREATION_SUCCESS';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';

export const ISSUES_FETCH_SUCCESS = 'ISSUES_FETCH_SUCCESS';
export const ISSUE_FETCH_SUCCESS = 'ISSUE_FETCH_SUCCESS';
export const ISSUE_CREATION_SUCCESS = 'ISSUE_CREATION_SUCCESS';
export const ISSUE_UPDATE_SUCCESS = 'ISSUE_UPDATE_SUCCESS';
